Improve CSS syntax error reporting
This produces tracebacks like the following:

    Traceback (most recent call last):
      ...
      File "/home/mg/src/zopefoundation/zc.catalog/.tox/py37/lib/python3.7/site-packages/zope/testbrowser/browser.py", line 1370, in getControlLabels
        forlbls = html.select('label[for=%s]' % controlid)
      File "/home/mg/src/zopefoundation/zc.catalog/.tox/py37/lib/python3.7/site-packages/bs4/element.py", line 1376, in select
        return soupsieve.select(selector, self, namespaces, limit, **kwargs)
      File "/home/mg/src/soupsieve/soupsieve/__init__.py", line 108, in select
        return compile(select, namespaces, flags).select(tag, limit)
      File "/home/mg/src/soupsieve/soupsieve/__init__.py", line 59, in compile
        return cp._cached_css_compile(pattern, namespaces, flags)
      File "/home/mg/src/soupsieve/soupsieve/css_parser.py", line 192, in _cached_css_compile
        CSSParser(pattern, flags).process_selectors(),
      File "/home/mg/src/soupsieve/soupsieve/css_parser.py", line 930, in process_selectors
        return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
      File "/home/mg/src/soupsieve/soupsieve/css_parser.py", line 772, in parse_selectors
        key, m = next(iselector)
      File "/home/mg/src/soupsieve/soupsieve/css_parser.py", line 917, in selector_iter
        raise SelectorSyntaxError(msg, self.pattern)
      File "<string>", line 1
        label[for=BrowserAdd__zope.catalog.catalog.Catalog]
             ^
    soupsieve.css_parser.SelectorSyntaxError: Malformed attribute selector at position 5

whereas before the traceback ended in

      File "/home/mg/src/zopefoundation/zc.catalog/.tox/py37/lib/python3.7/site-packages/soupsieve/css_parser.py", line 881, in selector_iter
        raise SyntaxError(msg)
      File "<string>", line None
    SyntaxError: Malformed attribute selector at position 5

making it difficult to see what exactly was malformed about the selector.

I've also chosen to introduce an exception subclass
(SelectorSyntaxError), so that CSS parse errors could be distinguished
from genuine Python syntax errors.